dispatch_address: "ctwx"
storage_path: "/storage"
log_config:
  location: "/tmp/wxedge.log"
  back_up_num: 3
  max_size_bytes: 3145728 # 3Mb
miner_config: 
  minion_interval: 120
  blacklist:
  - "CTJB"
  - "TSWX"
minion_config: 
  minion_report_interval: 60
tm_config:
  report_task_interval: 10
  keep_alive_interval: 60
dispatch_config:
  dump_file: "dump_task"
  report_interval: 120
  fetch_interval: 120
  task_type: 1
